[project]
name = "scripts"
version = "0.1.0"
description = "Some useful scripts for the tributary repository"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.4.4",
    "pyarrow>=23.0.0",
    "pydantic-ai-slim[openrouter]>=1.59.0",
]
